# Generated by Django 4.2 on 2025-03-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datapp.user', verbose_name='所属用户'),
        ),
    ]
